'use client';

// Auto-generated by scripts/generate-plugin-registry.mjs — DO NOT EDIT.
// Scans plugins/*/plugin.yaml for custom-react views and builds
// the dynamic import map. Re-run this script after adding/removing plugins.

import type { ComponentType } from 'react';
import type { HostComponentProps } from '../sdk';

export const pluginComponents: Record<
  string,
  () => Promise<{ default: ComponentType<any> }>
> = {
  'approvals': () => import('./approvals/index'),
  'claude-chat': () => import('./claude-chat/index'),
  'dashboard': () => import('./dashboard/index'),
  'mesh': () => import('./mesh/index'),
  'app-manager': () => import('./plugin-manager/index'),
  'terminal': () => import('./terminal/index'),
};
