'use client';

import { useState, useCallback } from 'react';
import { buildMenuItems } from '../menus/context-menu-registry';
import { getAction } from '../actions/action-registry';
import type { ActionRunContext } from '../actions/action-types';
import type { WhenContext } from '../../../lib/evaluate-when';
import type { CreateInstanceOptions } from '../../../lib/session-types';
import type {
  ContextMenuRequest,
  ContextMenuTarget,
  ContextMenuOpenHandler,
  ContextMenuItemSpec,
} from '../menus/context-menu-types';
import type { ContextMenuItem } from '../shell/context-menu';
import type { ResolvedContextMenuItem } from '../menus/context-menu-types';

/**
 * Host-owned context menu hook.
 *
 * Three-part model:
 *   1. Manifest menus (stable surfaces via contributes.menus)
 *   2. Action registry actions with 'contextMenu' surface
 *   3. Component localItems (runtime, dynamic, highest priority)
 *
 * Host owns rendering, positioning, and command dispatch.
 * Components call openContextMenu() with a ContextMenuRequest.
 *
 * Remaining debt (TODO):
 * - "New Instance" dynamic list is still generated by the hook because the
 *   action registry doesn't support parameterized sub-menus for dynamic
 *   adapter types. Should eventually come from a host.createInstance action
 *   or adapter capability provider rather than hook-level adapter-type enumeration.
 */
export function useContextMenu(
  actionRunCtx: ActionRunContext,
  whenCtx: WhenContext,
  getAllAdapterTypes: () => { id: string; meta: { label: string } }[],
  projectCwd: string,
  createInstance: (opts: CreateInstanceOptions) => unknown,
) {
  const [ctxMenu, setCtxMenu] = useState<{ x: number; y: number; items: ContextMenuItem[] } | null>(null);

  /**
   * Primary API: open a context menu from a ContextMenuRequest.
   * Builds items via context-menu-registry (manifest + action registry + localItems),
   * resolves commands, then sets state for the Host renderer.
   */
  const openContextMenu: ContextMenuOpenHandler = useCallback((request: ContextMenuRequest) => {
    request.event.preventDefault();
    request.event.stopPropagation?.();

    const resolved = buildMenuItems(request, actionRunCtx);

    // Convert ResolvedContextMenuItem[] to renderer's ContextMenuItem[]
    const items = resolvedToRenderItems(resolved);

    setCtxMenu({ x: request.event.clientX, y: request.event.clientY, items });
  }, [actionRunCtx]);

  /**
   * Default handler for right-click on the main workbench area.
   * Builds a ContextMenuRequest with:
   *  - target: workbench
   *  - chain: ["view/context", "workbench/context"]
   *  - localItems: "New X" items for each registered adapter type
   *
   * The "New <label>" items are dynamic — they reflect whatever
   * adapters are registered at call time.
   */
  const handleWorkbenchContextMenu = useCallback((e: React.MouseEvent) => {
    e.preventDefault();

    const allAdapterTypes = getAllAdapterTypes();
    const newInstanceItems: ContextMenuItemSpec[] = allAdapterTypes.map(a => ({
      id: `new.${a.id}`,
      title: `New ${a.meta.label}`,
      command: 'host.createInstance',
      args: { adapterId: a.id },
      group: 'navigation',
      order: 1,
    }));

    const target: ContextMenuTarget = {
      kind: 'workbench',
      view: whenCtx.view as string | undefined,
      adapterId: whenCtx.activeAdapterId as string | undefined,
      isRunning: !!(whenCtx.isRunning),
    };

    const request: ContextMenuRequest = {
      event: e,
      target,
      chain: ['view/context', 'workbench/context'],
      menu: 'workbench/context',
      localItems: newInstanceItems.length > 0
        ? [
            ...newInstanceItems,
            { id: 'sep.new', title: '', separator: true, order: 2, group: 'navigation' },
          ]
        : undefined,
      whenContext: { ...whenCtx },
    };

    const resolved = buildMenuItems(request, actionRunCtx);

    // Convert "host.createInstance" command to actual action closures
    // since the action registry doesn't have a generic host.createInstance action.
    const converted = resolved.map(item => {
      if (item.id.startsWith('new.') && !item.children) {
        const adapterId = item.id.replace('new.', '');
        return {
          ...item,
          action: () => createInstance({ dir: projectCwd || '.', adapterId }),
        };
      }
      return item;
    });

    const items = resolvedToRenderItems(converted);
    setCtxMenu({ x: e.clientX, y: e.clientY, items });
  }, [actionRunCtx, whenCtx, getAllAdapterTypes, projectCwd, createInstance]);

  const closeContextMenu = useCallback(() => {
    setCtxMenu(null);
  }, []);

  return {
    /** Context menu state for the Host renderer. */
    ctxMenu,
    /** Direct state setter (for backward compat with handleContextTab). */
    setCtxMenu,
    /** Open a context menu from a ContextMenuRequest. */
    openContextMenu,
    /** Default handler for workbench-area right-click. */
    handleWorkbenchContextMenu: handleWorkbenchContextMenu,
    /** Close the context menu. */
    closeContextMenu,
  };
}

// ─── Helpers ─────────────────────────────────────────────────

function resolvedToRenderItems(items: ResolvedContextMenuItem[]): ContextMenuItem[] {
  return items.map(item => ({
    label: item.label,
    shortcut: item.shortcut,
    action: item.action,
    disabled: item.disabled,
    danger: item.danger,
    divider: item.divider,
    group: item.group,
    order: item.order,
    icon: item.icon,
    checked: item.checked,
    disabledReason: item.disabledReason,
    children: item.children ? resolvedToRenderItems(item.children) : undefined,
  }));
}
